[[pages]]
name = "Section"
is_section = true
icon = "ğŸ "

[[pages]]
path = "startpage.py"
name = "Our Start Page"
icon = "ğŸˆï¸"

[[pages]]
path = "document_manager.py"
name = "Document Manager"
icon = "ğŸ“"
