[[pages]]
name = "Section"
is_section = true
icon = "ğŸ "

[[pages]]
path = "startpage.py"
name = "Rust exam project"
icon = ""

[[pages]]
path = "document_manager.py"
name = "Document Manager"
icon = "ğŸ“"
